services:
  localstack:
    image: localstack/localstack
    platform: linux/amd64
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=dynamodb
      - EDGE_PORT=4566
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./localstack:/var/lib/localstack
    healthcheck:
      test: ["CMD-SHELL", "curl -s -o /dev/null -w \"%{http_code}\" http://localhost:4566/_localstack/health | grep '200' || exit 1"]
      interval: 1s
      retries: 20
      start_period: 1s
      timeout: 5s
    networks:
      - localstack-network

  usersgrpc:
    build:
      context: ./
      dockerfile: ./Dockerfile
    platform: linux/amd64
    container_name: usersgrpc
    depends_on:
      localstack:
        condition: service_healthy
    environment:

      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
      - ./server:/app/server/
      - ./users:/app/users/
      - ./cmd:/app/cmd/
      - ./seed_db_with_test_data.sh:/usr/local/bin/seed_db_with_test_data.sh
    entrypoint: ["/bin/sh", "-c", "chmod +x /usr/local/bin/seed_db_with_test_data.sh && /usr/local/bin/seed_db_with_test_data.sh && /app/serverexecutable"]
    ports:
      - "50051:50051"
    networks:
      - localstack-network

volumes:
  localstack:

networks:
  localstack-network:
    driver: bridge
